language: python
sudo: false
notifications:
  email: false

matrix:
  fast_finish: true
  include:
  - python: 3.8
    env: CONDA_ENV=py38

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda env create --file ci/environment-$CONDA_ENV.yml
  - source activate repro
  - python -m ipykernel install --user --name repro --display-name "Py3-repro"

script:
  - papermill Tidal_forcing_TPXO9_OM5x5.ipynb output.ipynb
  - md5sum -c checksums_TPXO9.txt
