name: repro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - ipython
  - papermill
  - netcdf4
  - esmf
  - esmpy
  - matplotlib
  - cartopy
  - pip
  - toolz
  - dask
  - numpy
  - pip:
    - git+https://github.com/pydata/xarray.git
    - git+https://github.com/pangeo-data/xESMF.git
    - git+https://github.com/xgcm/xgcm.git
