name: repro
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - ipython
  - papermill
  - netcdf4
  - esmf=8.0.0
  - esmpy=8.0.0
  - matplotlib
  - cartopy
  - xarray
  - xesmf
  - xgcm
